apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: khelloworld
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: khelloworld # We added namespace for hellogopher
spec:
  ports:
  - port: 3306 # The ports to expose
  selector:
    app: mysql # Selector used to apply service on all Objects with label app=mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: khelloworld
data:
  DATABASE_USERNAME: root
  DATABASE_NAME: test
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: khelloworld
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dvcmQ=
